import { Aperture, Frame, House, MessageSquareText, Workflow } from 'lucide-react';
import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from 'next/link';
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > <div className="flex flex-row  bg-white text-black dark:bg-gray-900 dark:text-white">
          <div className="flex flex-col py-10 px-2 gap-8  items-center border border-r-gray-400"> 
            <Link href="/" className="flex flex-col items-center"><House/>Home</Link>
            <Link href="/graph?agent=stock_graph" className="flex flex-col items-center"><Workflow/>stock</Link>
            <Link href="/graph?agent=life" className="flex flex-col items-center"><MessageSquareText/>life</Link> 
            <Link href="/graph?agent=test_graph" className="flex flex-col items-center"><Frame/>test graph</Link> 
            <Link href="/flow" className="flex flex-col items-center"><Aperture/>flow</Link> 
          </div>
          <div className="flex-grow min-h-screen transition-colors duration-300">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
